# 4.1 The NumPy ndarray: A Multidimensional Array Onject
One of the key features of NumPy is its N-dimensional array object, or ndarray, which is a fast, flexible container for large datasets in Python. Arrays enable you to perform mathematical operations on whole blocks of data using similar syntax to the equivalent operations between scalar elements.

To give you a flavor of how NumPy enables batch computations with similar syntax to scalar values on built-in Python objects, I first import NumPy and create a small array:

## Creating ndarrays

In [16]:
import numpy as np

# Creating a numpy array
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [17]:
# Creating another numpy array
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
# returning dimensions of np array
arr2.ndim

2

In [19]:
# returning the shape of an np array
arr2.shape

(2, 4)

In [20]:
# returing data types of np arrays
print("Data type of arr1: ")
print(arr1.dtype)

print("Data type of arr2: ")
print(arr2.dtype)

Data type of arr1: 
float64
Data type of arr2: 
int64


In [21]:
# creating an array of all 0's
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
# creating multidemensional array of 0's
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [23]:
# creating an empty multidemensional array
np.empty((2, 3, 2))

array([[[1.18090437e-311, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [3.62483311e+228, 3.59904369e+179]],

       [[1.00592184e-070, 3.79976238e+175],
        [9.90747273e+164, 1.09751400e-071],
        [6.76033689e+170, 5.40221836e-062]]])

In [24]:
# creating a sorted array
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Arithmetic with NumPy Arrays

In [36]:
# creating array
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
# Arithmetic with Arrays
print("arr * arr:")
print(arr * arr)

print("arr - arr:")
print(arr - arr)

print("1 / arr:")
print(1 / arr)

print("arr **2:")
print(arr**2)

arr * arr:
[[ 1.  4.  9.]
 [16. 25. 36.]]
arr - arr:
[[0. 0. 0.]
 [0. 0. 0.]]
1 / arr:
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
arr **2:
[[ 1.  4.  9.]
 [16. 25. 36.]]


In [39]:
# Comparisons between arrays of the same size yield Boolean arrays:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

## Basic Indexing and Slicing

In [ ]:
# Initializing Array
arr = np.arange(10)

In [42]:
# Finding 5th index of array
print(arr[5])

5


In [43]:
# Finding 5th-8th index of array
print(arr[5:8])

[5 6 7]


In [44]:
# changing values of an array at a certain index
arr[5:8] = 12
print(arr)

[ 0  1  2  3  4 12 12 12  8  9]


In [45]:
# slicing an array
arr_slice = arr[5:8]
print(arr_slice)

[12 12 12]


In [46]:
# Changing values in slice effects the original arr values
arr_slice[1] = 12345
print(arr)

[    0     1     2     3     4    12 12345    12     8     9]


In [47]:
# Bare slice will assign values to all values in an array
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [48]:
# creating a 2d array for indexing

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
# finding array at second index
print(arr2d[2])

[7 8 9]


In [50]:
# finding second index in 0th index array
print(arr2d[0][2])

3


In [51]:
# crating a 3d array for indexing
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
# finding first 2x3 array
print(arr3d[0])

[[1 2 3]
 [4 5 6]]


### Both scalar values and arrays can be assigned to arr3d[0]:

In [54]:
old_values = arr3d[0].copy()
arr3d[0] = 42
print(arr3d)

[[[42 42 42]
  [42 42 42]]

 [[ 7  8  9]
  [10 11 12]]]


In [55]:
# assigning back old values
arr3d[0] = old_values
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [57]:
# finding the first 1x3 array in second 2x3 array
print(arr3d[1, 0])
print(arr3d[1][0])

[7 8 9]
[7 8 9]


### Indexing with slices

In [ ]:
# Like one-dimensional objects such as Python lists, ndarrays can be sliced with the familiar syntax:
print(arr[1:6])

[ 0  1  2  3  4 64 64 64  8  9]


In [63]:
# returning the first 2 arrays in arr2d
print(arr2d)
print("")
print(arr2d[:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]]


In [64]:
# returning the last two values of the first two arrays
print(arr2d)
print("")
print(arr2d[:2, 1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 3]
 [5 6]]


## Transposing Arrays and Swapping Axes

In [66]:
# creating an initial array
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
# Transposing array
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [69]:
# using transpose for matrix multiplication
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
print(arr)
print("")
np.dot(arr.T, arr)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]



array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [72]:
# swapping axes
print(arr)
print("")
arr.swapaxes(0,1)

[[ 0  1  0]
 [ 1  2 -2]
 [ 6  3  2]
 [-1  0 -1]
 [ 1  0  1]]



array([[ 0,  1,  6, -1,  1],
       [ 1,  2,  3,  0,  0],
       [ 0, -2,  2, -1,  1]])