A set of mathematical functions that compute statistics about an entire array or about the data along an axis are accessible as methods of the array class. You can use aggregations (sometimes called reductions) like sum, mean, and std (standard deviation) either by calling the array instance method or using the top-level NumPy function. When you use the NumPy function, like numpy.sum, you have to pass the array you want to aggregate as the first argument.

In [ ]:
# Finding mean and sum of entire array

import numpy as np
rng = np.random.default_rng(seed=12345)
arr = rng.standard_normal((5,4))
print(arr.mean())
print(arr.sum())

array([[-1.42382504,  1.26372846, -0.87066174, -0.25917323],
       [-0.07534331, -0.74088465, -1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306,  2.34740965,  0.96849691],
       [-0.75938718,  0.90219827, -0.46695317, -0.06068952],
       [ 0.78884434, -1.25666813,  0.57585751,  1.39897899]])

In [7]:
# finding mean and sum of specific rows/ columns 
# Here, arr.mean(axis=1) means "compute mean across the columns," where arr.sum(axis=0) means "compute sum down the rows."
print(arr.mean(axis=1))
print(arr.mean(axis=0))

[-0.32248289 -0.38378196  0.4310254  -0.0962079   0.37675318]
[-0.22173061 -0.35689782  0.04357191  0.53930119]


In [9]:
# Other methods like cumsum and cumprod do not aggregate, instead producing an array of the intermediate results:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr.cumsum())

[ 0  1  3  6 10 15 21 28]


In [11]:
# The expression arr.cumsum(axis=0) computes the cumulative sum along the rows, while arr.cumsum(axis=1) computes the sums along the columns:
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr)
print("")
print(arr.cumsum(axis=0))
print("")
print(arr.cumsum(axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]

[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
